const Account = require('./index');

describe('Account',()=>{
    let account, data, signature;
    beforeEach(()=>{
        account = new Account;
        data = {demo: "demo"};
        signature = account.sign(data);
      //  console.log(signature);
    });

    describe('verifySignature()',()=>{
        it('Validate signature generated by the account!!',()=>{
            expect(Account.verifySignature({publicKey: account.address,data,signature})).toBe(true);
        });

        it('Invalidates a signature not generated by the account',()=>{
            expect(Account.verifySignature({publicKey: new Account().address, data, signature})).toBe(false);
        });
});
});